### ISSUE TITLE
API token is invalid

### ISSUE THREAD

**Issue by kskarz** [dmfigol/simple-smartsheet#15]
Hi,

I receive the below error message:

Traceback (most recent call last):
  File "C:\Smartsheet\Smartsheet-Data-Tracker-master\simple.py", line 20, in <module>
    sheets = smartsheet.sheets.list()
  File "C:\Python\Python37-32\lib\site-packages\simple_smartsheet\crud.py", line 115, in list
    self.list_url, params={"includeAll": "true"}
  File "C:\Python\Python37-32\lib\site-packages\simple_smartsheet\smartsheet.py", line 88, in get
    raise exceptions.SmartsheetHTTPError.from_response(response)
simple_smartsheet.exceptions.SmartsheetHTTPClientError: HTTP response code 401 - Error code 1002 - Your Access Token is invalid.
[Finished in 1.404s]

The token is valid as it works with Smartsheet API.

**Comment by dmfigol** [comment]
sorry, I didn't setup any alerts on new issues and never saw it. Did you figure it out? If it is still not working, could you try using curl with your token and show the result?
https://smartsheet-platform.github.io/api-docs/#list-sheets
there is an example on the right side

**Comment by dmfigol** [comment]
I will close this. Feel free to re-open if the issue persists.
