### ISSUE TITLE
TypeError: Invalid first argument to register

### ISSUE THREAD

**Issue by bbaker1229** [dmfigol/simple-smartsheet#35]
Hello,

I am using simple_smartsheet version 0.5.0 with python 3.10.6 and after importing "Smartsheet" I am seeing the following error:

>>> from simple_smartsheet import Smartsheet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/simple_smartsheet/__init__.py", line 1, in <module>
    from .smartsheet import Smartsheet, AsyncSmartsheet
  File "/home/user/.local/lib/python3.10/site-packages/simple_smartsheet/smartsheet.py", line 8, in <module>
    from simple_smartsheet import exceptions
  File "/home/user/.local/lib/python3.10/site-packages/simple_smartsheet/exceptions.py", line 7, in <module>
    from simple_smartsheet.models.extra import Error
  File "/home/user/.local/lib/python3.10/site-packages/simple_smartsheet/models/__init__.py", line 1, in <module>
    from .cell import Cell
  File "/home/user/.local/lib/python3.10/site-packages/simple_smartsheet/models/cell.py", line 11, in <module>
    from simple_smartsheet.models.base import Schema, Object
  File "/home/user/.local/lib/python3.10/site-packages/simple_smartsheet/models/base.py", line 30, in <module>
    converter.register_structure_hook(IndexesType, lambda x, _: x)
  File "/home/user/.local/lib/python3.10/site-packages/cattrs/converters.py", line 280, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/home/user/.local/lib/python3.10/site-packages/cattrs/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/usr/lib/python3.10/functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. typing.Dict[typing.Tuple[str, ...], simple_smartsheet.types.IndexType] is not a class.

Any ideas on how to solve this?  Please let me know if there is any other information that is needed.  Thank you.

**Comment by kaminski-pawel** [comment]
The latest version of Python I managed to import Smartsheet from `simple-smartsheet` without any errors was Python 3.8.10. Unfortunately, as of today the library breaks down with Python 3.9 and newer (tested with Python 3.11.0a7, and 3.9.12).

**Comment by bbaker1229** [comment]
I created a pull request for this issue using the information from cattrs issue 206.  It seems to work for me.
https://github.com/python-attrs/cattrs/issues/206#issuecomment-1022792275

**Comment by dmfigol** [comment]
@bbaker1229 thank you for bringing this to my attention and sorry for not replying earlier. I will take a look and investigate this. This project has needed some love for quite some time and maybe it is the right time to do it.

**Comment by bbaker1229** [comment]
@dmfigol No problem.  I had started a pull request, but I cancelled it because the actual fix looks to be much more involved than I had originally thought.  It fixed my initial issue, but wasn't the complete solution.  Thank you for your work on this project.
